msg = ('Exercicio 001')
print(msg)
nome = input('Qual é seu nome ? ')
print('É um prezer em te conhecer {}!'.format(nome))
ano = input('Qual ano voce nasceu ? ')
print('Seu nome é {}, voce nasceu no ano de {}.'.format(nome,ano))
