msg = ('exercício 012')
print(msg)
preço = float(input('Qual é preço do Produto? R$ '))
novo = preço - (preço * 5 / 100)
print('O produto que custava R${:.2f}, na promoção com desconto de 5% vai custar R${:.2f}'.format(preço, novo))